### ISSUE TITLE
Run Tenon in localhost

### ISSUE THREAD

**Issue by acespace90** [tollwerk/fractal-tenon#1]
Hi, the public url of my site is protected by login, so is not public at all, but only for team purposes.

So is it possible to run and exectue Tenon in localhost?

**Comment by jkphl** [comment]
@acespace90 I never really tried that, to be honest. Tenon's usual way of testing websites is by fetching them via HTTP. (IIRC you can also send an HTML fragment to Tenon but how would you deal with linked resources like images & CSS then — can't send them all inline ...). Have you tried adding a username and password to the public URL in your `fractal.js`, like `https://user:password@fractal.example.com`? Maybe this works.

Btw. if this is something Tenon could improve: Karl Groves, the founder of Tenon, will visit me next week, so I could let him know. ;)

**Comment by acespace90** [comment]
@jkphl thanks I didn't think about it! With user and passw into the public URL it works! Anyway it would be great if in the future would be available local testing.

I've another question but maybe is better if I open another issue :)

**Comment by jkphl** [comment]
@acespace90 Glad that it worked. Local testing won't be available with Tenon, however, as Tenon is an online service only (and see my remark about the embedded resources above). Happy to wait for your next issue. ;)
